# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "frontend_cedric" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - uses: browser-actions/setup-chrome@latest
    - uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '106.0.5249.61'
    - run: npm ci --legacy-peer-deps
      working-directory: frontend
    - run: npm run test_w_server
      working-directory: frontend
    - run: npm run test_w_server
      working-directory: backend
